# Generated by Django 4.2 on 2023-04-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0004_remove_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exam_name', models.CharField(max_length=500)),
                ('Exam_id', models.CharField(max_length=500)),
                ('Name', models.CharField(max_length=500)),
                ('Roll_no', models.CharField(max_length=500)),
                ('clas', models.CharField(max_length=500)),
                ('section', models.CharField(max_length=500)),
            ],
        ),
    ]
