# Generated by Django 4.2 on 2023-04-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0005_qr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qr',
            old_name='clas',
            new_name='classes',
        ),
        migrations.AddField(
            model_name='qr',
            name='center_code',
            field=models.CharField(default=False, max_length=500),
        ),
    ]
