# Generated by Django 4.2 on 2023-05-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0006_rename_clas_qr_classes_qr_center_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr',
            name='subject',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='qr',
            name='center_code',
            field=models.CharField(max_length=500),
        ),
    ]
