# Generated by Django 4.2 on 2023-05-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0007_qr_subject_alter_qr_center_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('classes', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=10)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exam_id', models.IntegerField()),
                ('exam_name', models.CharField(max_length=255)),
                ('roll_no', models.CharField(max_length=10)),
            ],
        ),
    ]
