# Generated by Django 4.2 on 2023-05-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0009_alter_examscore_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examscore',
            name='classes',
            field=models.CharField(max_length=10),
        ),
    ]
